
      const elementsData = [
        {
          num: 1,
          sym: "H",
          name: "Hydrogen",
          mass: "1.008",
          cat: "reactive-nonmetal",
          col: 1,
          row: 1,
          phase: "Gas",
        },
        {
          num: 2,
          sym: "He",
          name: "Helium",
          mass: "4.0026",
          cat: "noble-gas",
          col: 18,
          row: 1,
          phase: "Gas",
        },
        {
          num: 3,
          sym: "Li",
          name: "Lithium",
          mass: "6.94",
          cat: "alkali-metal",
          col: 1,
          row: 2,
          phase: "Solid",
        },
        {
          num: 4,
          sym: "Be",
          name: "Beryllium",
          mass: "9.0122",
          cat: "alkaline-earth",
          col: 2,
          row: 2,
          phase: "Solid",
        },
        {
          num: 5,
          sym: "B",
          name: "Boron",
          mass: "10.81",
          cat: "metalloid",
          col: 13,
          row: 2,
          phase: "Solid",
        },
        {
          num: 6,
          sym: "C",
          name: "Carbon",
          mass: "12.011",
          cat: "reactive-nonmetal",
          col: 14,
          row: 2,
          phase: "Solid",
        },
        {
          num: 7,
          sym: "N",
          name: "Nitrogen",
          mass: "14.007",
          cat: "reactive-nonmetal",
          col: 15,
          row: 2,
          phase: "Gas",
        },
        {
          num: 8,
          sym: "O",
          name: "Oxygen",
          mass: "15.999",
          cat: "reactive-nonmetal",
          col: 16,
          row: 2,
          phase: "Gas",
        },
        {
          num: 9,
          sym: "F",
          name: "Fluorine",
          mass: "18.998",
          cat: "reactive-nonmetal",
          col: 17,
          row: 2,
          phase: "Gas",
        },
        {
          num: 10,
          sym: "Ne",
          name: "Neon",
          mass: "20.180",
          cat: "noble-gas",
          col: 18,
          row: 2,
          phase: "Gas",
        },
        {
          num: 11,
          sym: "Na",
          name: "Sodium",
          mass: "22.990",
          cat: "alkali-metal",
          col: 1,
          row: 3,
          phase: "Solid",
        },
        {
          num: 12,
          sym: "Mg",
          name: "Magnesium",
          mass: "24.305",
          cat: "alkaline-earth",
          col: 2,
          row: 3,
          phase: "Solid",
        },
        {
          num: 13,
          sym: "Al",
          name: "Aluminium",
          mass: "26.982",
          cat: "post-transition",
          col: 13,
          row: 3,
          phase: "Solid",
        },
        {
          num: 14,
          sym: "Si",
          name: "Silicon",
          mass: "28.085",
          cat: "metalloid",
          col: 14,
          row: 3,
          phase: "Solid",
        },
        {
          num: 15,
          sym: "P",
          name: "Phosphorus",
          mass: "30.974",
          cat: "reactive-nonmetal",
          col: 15,
          row: 3,
          phase: "Solid",
        },
        {
          num: 16,
          sym: "S",
          name: "Sulfur",
          mass: "32.06",
          cat: "reactive-nonmetal",
          col: 16,
          row: 3,
          phase: "Solid",
        },
        {
          num: 17,
          sym: "Cl",
          name: "Chlorine",
          mass: "35.45",
          cat: "reactive-nonmetal",
          col: 17,
          row: 3,
          phase: "Gas",
        },
        {
          num: 18,
          sym: "Ar",
          name: "Argon",
          mass: "39.948",
          cat: "noble-gas",
          col: 18,
          row: 3,
          phase: "Gas",
        },
        {
          num: 19,
          sym: "K",
          name: "Potassium",
          mass: "39.098",
          cat: "alkali-metal",
          col: 1,
          row: 4,
          phase: "Solid",
        },
        {
          num: 20,
          sym: "Ca",
          name: "Calcium",
          mass: "40.078",
          cat: "alkaline-earth",
          col: 2,
          row: 4,
          phase: "Solid",
        },
        {
          num: 21,
          sym: "Sc",
          name: "Scandium",
          mass: "44.956",
          cat: "transition-metal",
          col: 3,
          row: 4,
          phase: "Solid",
        },
        {
          num: 22,
          sym: "Ti",
          name: "Titanium",
          mass: "47.867",
          cat: "transition-metal",
          col: 4,
          row: 4,
          phase: "Solid",
        },
        {
          num: 23,
          sym: "V",
          name: "Vanadium",
          mass: "50.942",
          cat: "transition-metal",
          col: 5,
          row: 4,
          phase: "Solid",
        },
        {
          num: 24,
          sym: "Cr",
          name: "Chromium",
          mass: "51.996",
          cat: "transition-metal",
          col: 6,
          row: 4,
          phase: "Solid",
        },
        {
          num: 25,
          sym: "Mn",
          name: "Manganese",
          mass: "54.938",
          cat: "transition-metal",
          col: 7,
          row: 4,
          phase: "Solid",
        },
        {
          num: 26,
          sym: "Fe",
          name: "Iron",
          mass: "55.845",
          cat: "transition-metal",
          col: 8,
          row: 4,
          phase: "Solid",
        },
        {
          num: 27,
          sym: "Co",
          name: "Cobalt",
          mass: "58.933",
          cat: "transition-metal",
          col: 9,
          row: 4,
          phase: "Solid",
        },
        {
          num: 28,
          sym: "Ni",
          name: "Nickel",
          mass: "58.693",
          cat: "transition-metal",
          col: 10,
          row: 4,
          phase: "Solid",
        },
        {
          num: 29,
          sym: "Cu",
          name: "Copper",
          mass: "63.546",
          cat: "transition-metal",
          col: 11,
          row: 4,
          phase: "Solid",
        },
        {
          num: 30,
          sym: "Zn",
          name: "Zinc",
          mass: "65.38",
          cat: "transition-metal",
          col: 12,
          row: 4,
          phase: "Solid",
        },
        {
          num: 31,
          sym: "Ga",
          name: "Gallium",
          mass: "69.723",
          cat: "post-transition",
          col: 13,
          row: 4,
          phase: "Solid",
        },
        {
          num: 32,
          sym: "Ge",
          name: "Germanium",
          mass: "72.630",
          cat: "metalloid",
          col: 14,
          row: 4,
          phase: "Solid",
        },
        {
          num: 33,
          sym: "As",
          name: "Arsenic",
          mass: "74.922",
          cat: "metalloid",
          col: 15,
          row: 4,
          phase: "Solid",
        },
        {
          num: 34,
          sym: "Se",
          name: "Selenium",
          mass: "78.971",
          cat: "reactive-nonmetal",
          col: 16,
          row: 4,
          phase: "Solid",
        },
        {
          num: 35,
          sym: "Br",
          name: "Bromine",
          mass: "79.904",
          cat: "reactive-nonmetal",
          col: 17,
          row: 4,
          phase: "Liquid",
        },
        {
          num: 36,
          sym: "Kr",
          name: "Krypton",
          mass: "83.798",
          cat: "noble-gas",
          col: 18,
          row: 4,
          phase: "Gas",
        },
        {
          num: 37,
          sym: "Rb",
          name: "Rubidium",
          mass: "85.468",
          cat: "alkali-metal",
          col: 1,
          row: 5,
          phase: "Solid",
        },
        {
          num: 38,
          sym: "Sr",
          name: "Strontium",
          mass: "87.62",
          cat: "alkaline-earth",
          col: 2,
          row: 5,
          phase: "Solid",
        },
        {
          num: 39,
          sym: "Y",
          name: "Yttrium",
          mass: "88.906",
          cat: "transition-metal",
          col: 3,
          row: 5,
          phase: "Solid",
        },
        {
          num: 40,
          sym: "Zr",
          name: "Zirconium",
          mass: "91.224",
          cat: "transition-metal",
          col: 4,
          row: 5,
          phase: "Solid",
        },
        {
          num: 41,
          sym: "Nb",
          name: "Niobium",
          mass: "92.906",
          cat: "transition-metal",
          col: 5,
          row: 5,
          phase: "Solid",
        },
        {
          num: 42,
          sym: "Mo",
          name: "Molybdenum",
          mass: "95.95",
          cat: "transition-metal",
          col: 6,
          row: 5,
          phase: "Solid",
        },
        {
          num: 43,
          sym: "Tc",
          name: "Technetium",
          mass: "98",
          cat: "transition-metal",
          col: 7,
          row: 5,
          phase: "Solid",
        },
        {
          num: 44,
          sym: "Ru",
          name: "Ruthenium",
          mass: "101.07",
          cat: "transition-metal",
          col: 8,
          row: 5,
          phase: "Solid",
        },
        {
          num: 45,
          sym: "Rh",
          name: "Rhodium",
          mass: "102.91",
          cat: "transition-metal",
          col: 9,
          row: 5,
          phase: "Solid",
        },
        {
          num: 46,
          sym: "Pd",
          name: "Palladium",
          mass: "106.42",
          cat: "transition-metal",
          col: 10,
          row: 5,
          phase: "Solid",
        },
        {
          num: 47,
          sym: "Ag",
          name: "Silver",
          mass: "107.87",
          cat: "transition-metal",
          col: 11,
          row: 5,
          phase: "Solid",
        },
        {
          num: 48,
          sym: "Cd",
          name: "Cadmium",
          mass: "112.41",
          cat: "transition-metal",
          col: 12,
          row: 5,
          phase: "Solid",
        },
        {
          num: 49,
          sym: "In",
          name: "Indium",
          mass: "114.82",
          cat: "post-transition",
          col: 13,
          row: 5,
          phase: "Solid",
        },
        {
          num: 50,
          sym: "Sn",
          name: "Tin",
          mass: "118.71",
          cat: "post-transition",
          col: 14,
          row: 5,
          phase: "Solid",
        },
        {
          num: 51,
          sym: "Sb",
          name: "Antimony",
          mass: "121.76",
          cat: "metalloid",
          col: 15,
          row: 5,
          phase: "Solid",
        },
        {
          num: 52,
          sym: "Te",
          name: "Tellurium",
          mass: "127.60",
          cat: "metalloid",
          col: 16,
          row: 5,
          phase: "Solid",
        },
        {
          num: 53,
          sym: "I",
          name: "Iodine",
          mass: "126.90",
          cat: "reactive-nonmetal",
          col: 17,
          row: 5,
          phase: "Solid",
        },
        {
          num: 54,
          sym: "Xe",
          name: "Xenon",
          mass: "131.29",
          cat: "noble-gas",
          col: 18,
          row: 5,
          phase: "Gas",
        },
        {
          num: 55,
          sym: "Cs",
          name: "Caesium",
          mass: "132.91",
          cat: "alkali-metal",
          col: 1,
          row: 6,
          phase: "Solid",
        },
        {
          num: 56,
          sym: "Ba",
          name: "Barium",
          mass: "137.33",
          cat: "alkaline-earth",
          col: 2,
          row: 6,
          phase: "Solid",
        },
        {
          num: 72,
          sym: "Hf",
          name: "Hafnium",
          mass: "178.49",
          cat: "transition-metal",
          col: 4,
          row: 6,
          phase: "Solid",
        },
        {
          num: 73,
          sym: "Ta",
          name: "Tantalum",
          mass: "180.95",
          cat: "transition-metal",
          col: 5,
          row: 6,
          phase: "Solid",
        },
        {
          num: 74,
          sym: "W",
          name: "Tungsten",
          mass: "183.84",
          cat: "transition-metal",
          col: 6,
          row: 6,
          phase: "Solid",
        },
        {
          num: 75,
          sym: "Re",
          name: "Rhenium",
          mass: "186.21",
          cat: "transition-metal",
          col: 7,
          row: 6,
          phase: "Solid",
        },
        {
          num: 76,
          sym: "Os",
          name: "Osmium",
          mass: "190.23",
          cat: "transition-metal",
          col: 8,
          row: 6,
          phase: "Solid",
        },
        {
          num: 77,
          sym: "Ir",
          name: "Iridium",
          mass: "192.22",
          cat: "transition-metal",
          col: 9,
          row: 6,
          phase: "Solid",
        },
        {
          num: 78,
          sym: "Pt",
          name: "Platinum",
          mass: "195.08",
          cat: "transition-metal",
          col: 10,
          row: 6,
          phase: "Solid",
        },
        {
          num: 79,
          sym: "Au",
          name: "Gold",
          mass: "196.97",
          cat: "transition-metal",
          col: 11,
          row: 6,
          phase: "Solid",
        },
        {
          num: 80,
          sym: "Hg",
          name: "Mercury",
          mass: "200.59",
          cat: "transition-metal",
          col: 12,
          row: 6,
          phase: "Liquid",
        },
        {
          num: 81,
          sym: "Tl",
          name: "Thallium",
          mass: "204.38",
          cat: "post-transition",
          col: 13,
          row: 6,
          phase: "Solid",
        },
        {
          num: 82,
          sym: "Pb",
          name: "Lead",
          mass: "207.2",
          cat: "post-transition",
          col: 14,
          row: 6,
          phase: "Solid",
        },
        {
          num: 83,
          sym: "Bi",
          name: "Bismuth",
          mass: "208.98",
          cat: "post-transition",
          col: 15,
          row: 6,
          phase: "Solid",
        },
        {
          num: 84,
          sym: "Po",
          name: "Polonium",
          mass: "209",
          cat: "post-transition",
          col: 16,
          row: 6,
          phase: "Solid",
        },
        {
          num: 85,
          sym: "At",
          name: "Astatine",
          mass: "210",
          cat: "metalloid",
          col: 17,
          row: 6,
          phase: "Solid",
        },
        {
          num: 86,
          sym: "Rn",
          name: "Radon",
          mass: "222",
          cat: "noble-gas",
          col: 18,
          row: 6,
          phase: "Gas",
        },
        {
          num: 87,
          sym: "Fr",
          name: "Francium",
          mass: "223",
          cat: "alkali-metal",
          col: 1,
          row: 7,
          phase: "Solid",
        },
        {
          num: 88,
          sym: "Ra",
          name: "Radium",
          mass: "226",
          cat: "alkaline-earth",
          col: 2,
          row: 7,
          phase: "Solid",
        },
        {
          num: 104,
          sym: "Rf",
          name: "Rutherfordium",
          mass: "267",
          cat: "transition-metal",
          col: 4,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 105,
          sym: "Db",
          name: "Dubnium",
          mass: "268",
          cat: "transition-metal",
          col: 5,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 106,
          sym: "Sg",
          name: "Seaborgium",
          mass: "269",
          cat: "transition-metal",
          col: 6,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 107,
          sym: "Bh",
          name: "Bohrium",
          mass: "270",
          cat: "transition-metal",
          col: 7,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 108,
          sym: "Hs",
          name: "Hassium",
          mass: "269",
          cat: "transition-metal",
          col: 8,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 109,
          sym: "Mt",
          name: "Meitnerium",
          mass: "278",
          cat: "unknown",
          col: 9,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 110,
          sym: "Ds",
          name: "Darmstadtium",
          mass: "281",
          cat: "unknown",
          col: 10,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 111,
          sym: "Rg",
          name: "Roentgenium",
          mass: "282",
          cat: "unknown",
          col: 11,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 112,
          sym: "Cn",
          name: "Copernicium",
          mass: "285",
          cat: "transition-metal",
          col: 12,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 113,
          sym: "Nh",
          name: "Nihonium",
          mass: "286",
          cat: "unknown",
          col: 13,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 114,
          sym: "Fl",
          name: "Flerovium",
          mass: "289",
          cat: "post-transition",
          col: 14,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 115,
          sym: "Mc",
          name: "Moscovium",
          mass: "290",
          cat: "unknown",
          col: 15,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 116,
          sym: "Lv",
          name: "Livermorium",
          mass: "293",
          cat: "unknown",
          col: 16,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 117,
          sym: "Ts",
          name: "Tennessine",
          mass: "294",
          cat: "unknown",
          col: 17,
          row: 7,
          phase: "Synthetic",
        },
        {
          num: 118,
          sym: "Og",
          name: "Oganesson",
          mass: "294",
          cat: "unknown",
          col: 18,
          row: 7,
          phase: "Synthetic",
        },

        // Lanthanides
        {
          num: 57,
          sym: "La",
          name: "Lanthanum",
          mass: "138.91",
          cat: "lanthanide",
          col: 4,
          row: 9,
          phase: "Solid",
        },
        {
          num: 58,
          sym: "Ce",
          name: "Cerium",
          mass: "140.12",
          cat: "lanthanide",
          col: 5,
          row: 9,
          phase: "Solid",
        },
        {
          num: 59,
          sym: "Pr",
          name: "Praseodymium",
          mass: "140.91",
          cat: "lanthanide",
          col: 6,
          row: 9,
          phase: "Solid",
        },
        {
          num: 60,
          sym: "Nd",
          name: "Neodymium",
          mass: "144.24",
          cat: "lanthanide",
          col: 7,
          row: 9,
          phase: "Solid",
        },
        {
          num: 61,
          sym: "Pm",
          name: "Promethium",
          mass: "145",
          cat: "lanthanide",
          col: 8,
          row: 9,
          phase: "Solid",
        },
        {
          num: 62,
          sym: "Sm",
          name: "Samarium",
          mass: "150.36",
          cat: "lanthanide",
          col: 9,
          row: 9,
          phase: "Solid",
        },
        {
          num: 63,
          sym: "Eu",
          name: "Europium",
          mass: "151.96",
          cat: "lanthanide",
          col: 10,
          row: 9,
          phase: "Solid",
        },
        {
          num: 64,
          sym: "Gd",
          name: "Gadolinium",
          mass: "157.25",
          cat: "lanthanide",
          col: 11,
          row: 9,
          phase: "Solid",
        },
        {
          num: 65,
          sym: "Tb",
          name: "Terbium",
          mass: "158.93",
          cat: "lanthanide",
          col: 12,
          row: 9,
          phase: "Solid",
        },
        {
          num: 66,
          sym: "Dy",
          name: "Dysprosium",
          mass: "162.50",
          cat: "lanthanide",
          col: 13,
          row: 9,
          phase: "Solid",
        },
        {
          num: 67,
          sym: "Ho",
          name: "Holmium",
          mass: "164.93",
          cat: "lanthanide",
          col: 14,
          row: 9,
          phase: "Solid",
        },
        {
          num: 68,
          sym: "Er",
          name: "Erbium",
          mass: "167.26",
          cat: "lanthanide",
          col: 15,
          row: 9,
          phase: "Solid",
        },
        {
          num: 69,
          sym: "Tm",
          name: "Thulium",
          mass: "168.93",
          cat: "lanthanide",
          col: 16,
          row: 9,
          phase: "Solid",
        },
        {
          num: 70,
          sym: "Yb",
          name: "Ytterbium",
          mass: "173.05",
          cat: "lanthanide",
          col: 17,
          row: 9,
          phase: "Solid",
        },
        {
          num: 71,
          sym: "Lu",
          name: "Lutetium",
          mass: "174.97",
          cat: "lanthanide",
          col: 18,
          row: 9,
          phase: "Solid",
        },

        // Actinides
        {
          num: 89,
          sym: "Ac",
          name: "Actinium",
          mass: "227",
          cat: "actinide",
          col: 4,
          row: 10,
          phase: "Solid",
        },
        {
          num: 90,
          sym: "Th",
          name: "Thorium",
          mass: "232.04",
          cat: "actinide",
          col: 5,
          row: 10,
          phase: "Solid",
        },
        {
          num: 91,
          sym: "Pa",
          name: "Protactinium",
          mass: "231.04",
          cat: "actinide",
          col: 6,
          row: 10,
          phase: "Solid",
        },
        {
          num: 92,
          sym: "U",
          name: "Uranium",
          mass: "238.03",
          cat: "actinide",
          col: 7,
          row: 10,
          phase: "Solid",
        },
        {
          num: 93,
          sym: "Np",
          name: "Neptunium",
          mass: "237",
          cat: "actinide",
          col: 8,
          row: 10,
          phase: "Solid",
        },
        {
          num: 94,
          sym: "Pu",
          name: "Plutonium",
          mass: "244",
          cat: "actinide",
          col: 9,
          row: 10,
          phase: "Solid",
        },
        {
          num: 95,
          sym: "Am",
          name: "Americium",
          mass: "243",
          cat: "actinide",
          col: 10,
          row: 10,
          phase: "Solid",
        },
        {
          num: 96,
          sym: "Cm",
          name: "Curium",
          mass: "247",
          cat: "actinide",
          col: 11,
          row: 10,
          phase: "Solid",
        },
        {
          num: 97,
          sym: "Bk",
          name: "Berkelium",
          mass: "247",
          cat: "actinide",
          col: 12,
          row: 10,
          phase: "Solid",
        },
        {
          num: 98,
          sym: "Cf",
          name: "Californium",
          mass: "251",
          cat: "actinide",
          col: 13,
          row: 10,
          phase: "Solid",
        },
        {
          num: 99,
          sym: "Es",
          name: "Einsteinium",
          mass: "252",
          cat: "actinide",
          col: 14,
          row: 10,
          phase: "Solid",
        },
        {
          num: 100,
          sym: "Fm",
          name: "Fermium",
          mass: "257",
          cat: "actinide",
          col: 15,
          row: 10,
          phase: "Solid",
        },
        {
          num: 101,
          sym: "Md",
          name: "Mendelevium",
          mass: "258",
          cat: "actinide",
          col: 16,
          row: 10,
          phase: "Solid",
        },
        {
          num: 102,
          sym: "No",
          name: "Nobelium",
          mass: "259",
          cat: "actinide",
          col: 17,
          row: 10,
          phase: "Solid",
        },
        {
          num: 103,
          sym: "Lr",
          name: "Lawrencium",
          mass: "266",
          cat: "actinide",
          col: 18,
          row: 10,
          phase: "Solid",
        },
      ];

      const tableContainer = document.getElementById("periodic-table");

      function renderTable() {
        tableContainer.innerHTML = "";
        for (let r = 1; r <= 7; r++) {
          for (let c = 1; c <= 18; c++) {
            const elData = elementsData.find((e) => e.row === r && e.col === c);
            if (elData) {
              tableContainer.appendChild(createElementNode(elData));
            } else if (r === 6 && c === 3) {
              const marker = document.createElement("div");
              marker.className = "lanthanide-marker";
              marker.innerText = "57-71";
              tableContainer.appendChild(marker);
            } else if (r === 7 && c === 3) {
              const marker = document.createElement("div");
              marker.className = "actinide-marker";
              marker.innerText = "89-103";
              tableContainer.appendChild(marker);
            } else {
              const gap = document.createElement("div");
              gap.className = "gap";
              tableContainer.appendChild(gap);
            }
          }
        }

        const spacer = document.createElement("div");
        spacer.className = "series-spacer";
        tableContainer.appendChild(spacer);

        for (let r = 9; r <= 10; r++) {
          for (let c = 1; c <= 18; c++) {
            const elData = elementsData.find((e) => e.row === r && e.col === c);
            if (elData) {
              tableContainer.appendChild(createElementNode(elData));
            } else {
              const gap = document.createElement("div");
              gap.className = "gap";
              tableContainer.appendChild(gap);
            }
          }
        }
      }

      function createElementNode(data) {
        const el = document.createElement("div");
        el.className = `element ${data.cat}`;
        el.dataset.category = data.cat;
        el.style.gridColumn = data.col;
        el.style.gridRow = data.row;

        el.innerHTML = `
                <span class="number">${data.num}</span>
                <span class="symbol">${data.sym}</span>
                <span class="name">${data.name}</span>
            `;

        el.addEventListener("click", () => openModal(data));
        return el;
      }

      document.querySelectorAll(".filter-btn").forEach((btn) => {
        btn.addEventListener("click", (e) => {
          document
            .querySelectorAll(".filter-btn")
            .forEach((b) => b.classList.remove("active"));
          e.target.classList.add("active");

          const selectedCat = e.target.dataset.category;
          document.querySelectorAll(".element").forEach((el) => {
            if (selectedCat === "all" || el.dataset.category === selectedCat) {
              el.classList.remove("dimmed");
            } else {
              el.classList.add("dimmed");
            }
          });
        });
      });

      const modal = document.getElementById("modal");
      const closeModal = document.getElementById("close-modal");

      function openModal(data) {
        document.getElementById("m-symbol").innerText = data.sym;
        document.getElementById("m-name").innerText = data.name;
        document.getElementById("m-category").innerText = data.cat
          .replace("-", " ")
          .toUpperCase();
        document.getElementById("m-number").innerText = data.num;
        document.getElementById("m-mass").innerText = data.mass + " u";
        document.getElementById("m-group").innerText =
          `${data.col} / ${data.row > 7 ? (data.row === 9 ? "Lanthanide" : "Actinide") : data.row}`;
        document.getElementById("m-phase").innerText = data.phase;
        modal.classList.add("active");
      }

      closeModal.addEventListener("click", () =>
        modal.classList.remove("active"),
      );
      modal.addEventListener("click", (e) => {
        if (e.target === modal) modal.classList.remove("active");
      });

      renderTable();
